/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class Window32 */

#ifndef _Included_Window32
#define _Included_Window32
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Window32
 * Method:    FindWindow
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_window32_Window32_FindWindow
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     Window32
 * Method:    FindWindowEx
 * Signature: (IILjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_window32_Window32_FindWindowEx
  (JNIEnv *, jobject, jint, jint, jstring, jstring);

/*
 * Class:     Window32
 * Method:    SendMessage
 * Signature: (IIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_window32_Window32_SendMessage__IIILjava_lang_String_2
  (JNIEnv *, jobject, jint, jint, jint, jstring);

/*
 * Class:     Window32
 * Method:    SendMessage
 * Signature: (IIII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_window32_Window32_SendMessage__IIII
  (JNIEnv *, jobject, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
